import mongoose from "mongoose";

const DoctorSchema = mongoose.Schema({
  doctorName: { type: String, required: true },
  doctorDateOfBirth: { type: String, required: true },
  doctorPhone: { type: String, required: true },
  doctorEmail: { type: String, required: true, unique: true },
  doctorPassword: { type: String, required: true },
  nationalID: { type: String, required: true, unique: true },
  Gender: { type: String, enum: ["Male", "Female"], required: true },
  doctorImage: { type: String, default: null },
  field: {
    type: String,
    enum: [
      "Cardiology",
      "Dermatology",
      "Endocrinology",
      "Gastroenterology",
      "Hematology",
      "Immunology",
      "Neurology",
      "Oncology",
      "Orthopedics",
      "Pediatrics",
      "Pulmonology",
      "Radiology",
      "Rheumatology",
      "Urology",
      "Anesthesiology",
      "Emergency Medicine",
      "Family Medicine",
      "General Surgery",
      "Infectious Disease",
      "Nephrology",
      "Obstetrics and Gynecology",
      "Ophthalmology",
      "Otolaryngology",
      "Pathology",
      "Physical Medicine and Rehabilitation",
      "Plastic Surgery",
      "Psychiatry",
      "Public Health",
      "Sports Medicine",
      "Thoracic Surgery",
      "Vascular Surgery",
      "Geriatrics",
      "Palliative Care",
      "Medical Genetics",
      "Neonatology",
      "Nuclear Medicine",
      "Pain Management",
      "Dentistry",
      "Orthodontics",
      "Prosthodontics",
      "Endodontics",
      "Periodontics",
      "Oral and Maxillofacial Surgery",
    ],
    required: true,
  },
  yearsOfExprience: String,
  syndicateID: { type: String, required: true },
  syndicateCard: { type: String, required: true, default: null },
  certificates: [{ type: String, default: null }],
  clinic: [
    {
      clinicLicense: { type: String, default: null },
      clinicCity: { type: String, required: true },
      clinicArea: { type: String, required: true },
      clinicAddress: { type: String, required: true },
      clinicPhone: { type: [String], required: true },
      clinicEmail: { type: String, required: true },
      clinicWebsite: { type: String, required: true },
      clinicWorkDays: [
        {
          day: {
            type: String,
            enum: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
            required: true,
          },
          workingHours: { type: [String], required: true },
          examinationDuration: { type: Number, required: true },
        },
      ],
      clinicLocationLinks: { type: String, required: true },
      Price: { type: Number, required: true },
    },
  ],
});

const Doctor = mongoose.model("Doctor", DoctorSchema);

export default Doctor;
